FROM golang:latest as builder
RUN mkdir /app
WORKDIR /app
ENV GO111MODULE=on
COPY . .
RUN go mod download
WORKDIR /app/gateway/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o shippy-service-consignment
# Run container
#FROM alpine:latest
#RUN apk --no-cache add ca-certificates
#RUN mkdir /app
#WORKDIR /app
#COPY --from=builder /app .
#Expose port 8080 to the outside world
EXPOSE 8081
CMD ["./shippy-service-consignment"]